const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={category:null,questions:[],index:0,score:0,correct:0,start:0,elapsed:0,timer:null,hint:false,theme:localStorage.getItem("in2ition_theme")||"neon",sound:localStorage.getItem("in2ition_sound")!=="off"};
function showScreen(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");if(id==="homeScreen")renderHome();if(id==="achievementsScreen")renderAchievements();if(id==="leaderboardScreen")renderBoards();if(id==="categoryScreen")renderCategoryProgress()}
function renderHome(){let p=getProgress();$("#homePoints").textContent=p.totalPoints||0;$("#homeBadges").textContent=(p.badges||[]).length;$("#homeTrophies").textContent=(p.trophies||[]).length}
function renderCategoryProgress(){let p=getProgress(),d=p.completed||{};$("#categoryProgress").innerHTML=["Numbers","Colours","Animals","Random"].map(c=>`<div class="progress-item"><span>${c==="Numbers"?"🔢":c==="Colours"?"🎨":c==="Animals"?"🐾":"🎲"} ${c}</span><b>${d[c]?"✓ Complete":"Not completed"}</b></div>`).join("")}
function norm(s){return s.toLowerCase().trim().replace(/[.,!?'"’]/g,"").replace(/\s+/g," ")}
function startGame(cat,qs=null){state.category=cat;state.questions=qs||IN2ITION_QUESTIONS[cat];state.index=0;state.score=0;state.correct=0;state.start=Date.now();state.elapsed=0;state.hint=false;clearInterval(state.timer);state.timer=setInterval(()=>{$("#gameTimer").textContent=((Date.now()-state.start)/1000).toFixed(1)},100);showScreen("gameScreen");loadQuestion()}
function loadQuestion(){let q=state.questions[state.index];$("#gameCategory").textContent=state.category;$("#gameDifficulty").textContent=q.difficulty.toUpperCase();$("#clueText").textContent=q.clue;$("#answerInput").value="";$("#feedback").textContent="";$("#feedback").className="feedback";$("#hintText").textContent="";$("#answerArea").classList.remove("hidden");$("#revealArea").classList.add("hidden");$("#gameScore").textContent=state.score;$("#gameProgress").style.width=((state.index/state.questions.length)*100)+"%";$("#answerInput").focus()}
function submit(){let q=state.questions[state.index],g=norm($("#answerInput").value);if(!g)return toast("Type your guess first!");if(q.answer.some(a=>norm(a)===g)){state.correct++;state.score+=q.points;$("#revealImage").textContent=q.image;$("#revealAnswer").textContent=q.answer[0].toUpperCase();$("#earnedPoints").textContent=`+${q.points} POINTS`;$("#answerArea").classList.add("hidden");$("#revealArea").classList.remove("hidden");IN2ITION_ANIM.reveal();beep(660,.08)}else{$("#feedback").textContent="Not quite — try again!";$("#feedback").className="feedback bad";beep(180,.08)}}
function next(){state.index++;state.index<state.questions.length?loadQuestion():finish()}
function finish(){clearInterval(state.timer);state.elapsed=(Date.now()-state.start)/1000;let p=getProgress();p.totalPoints=(p.totalPoints||0)+state.score;p.completed=p.completed||{};p.trophies=p.trophies||[];p.completed[state.category]=true;if(!p.trophies.includes(state.category))p.trophies.push(state.category);if(state.correct===state.questions.length)unlockAchievement("perfect");if(state.category==="Random")unlockAchievement("random_master");if((p.badges||[]).length>=10)unlockAchievement("collector");saveProgress(p);IN2ITION_LEADERBOARD.add(state.category,state.score,state.elapsed);$("#resultPoints").textContent=state.score;$("#resultTime").textContent=state.elapsed.toFixed(1)+"s";$("#resultCorrect").textContent=`${state.correct}/${state.questions.length}`;$("#resultTitle").textContent=state.category==="Random"?"FINAL CHALLENGE COMPLETE!":"CATEGORY COMPLETE!";$("#resultMessage").textContent=state.correct===state.questions.length?"Perfect run! New achievement progress earned.":"Challenge complete — keep practicing!";$("#resultBadge").textContent=state.category==="Numbers"?"🔢":state.category==="Colours"?"🎨":state.category==="Animals"?"🐾":"🎲";showScreen("resultScreen");IN2ITION_ANIM.trophy()}
function hint(){if(state.hint)return toast("Hint already used.");state.hint=true;$("#hintText").textContent="Hint: starts with “"+state.questions[state.index].answer[0][0].toUpperCase()+"”";toast("Hint used")}
function renderAchievements(){let b=getProgress().badges||[];$("#achievementGrid").innerHTML=IN2ITION_ACHIEVEMENTS.map(a=>`<div class="achievement ${b.includes(a.id)?"unlocked":""}"><div class="badge">${a.icon}</div><h3>${a.title}</h3><p>${a.desc}</p></div>`).join("")}
function renderBoards(type="points"){let rows=type==="time"?IN2ITION_LEADERBOARD.time():IN2ITION_LEADERBOARD.points();$("#leaderboardList").innerHTML=rows.length?rows.map((r,i)=>`<div class="score-row"><div class="rank">#${i+1}</div><div><b>${r.category}</b><small>${new Date(r.date).toLocaleDateString()}</small></div><strong>${type==="time"?r.time.toFixed(1)+"s":r.points}</strong></div>`).join(""):`<div class="challenge-card"><h2>No scores yet</h2><p>Play a category to set your first score.</p></div>`}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1700)}
function beep(f,d){if(!state.sound)return;try{let C=AudioContext||webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d)}catch(e){}}
function theme(){let a=["neon","light","ocean"],i=a.indexOf(state.theme);state.theme=a[(i+1)%a.length];document.body.className=state.theme==="light"?"light":state.theme==="ocean"?"ocean":"";$("#themeName").textContent=state.theme==="light"?"Light":state.theme==="ocean"?"Ocean":"Neon Night";localStorage.setItem("in2ition_theme",state.theme)}
$$("[data-screen]").forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$$(".category-card").forEach(b=>b.onclick=()=>startGame(b.dataset.category));
$("#playBtn").onclick=()=>showScreen("categoryScreen");$("#homeBtn").onclick=()=>showScreen("homeScreen");$("#themeBtn").onclick=theme;$("#themeCycle").onclick=theme;$("#submitBtn").onclick=submit;$("#nextBtn").onclick=next;$("#hintBtn").onclick=hint;$("#answerInput").onkeydown=e=>{if(e.key==="Enter")submit()};$("#continueBtn").onclick=()=>showScreen("categoryScreen");
$$(".tab").forEach(t=>t.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");renderBoards(t.dataset.board)});
$("#soundToggle").onclick=()=>{state.sound=!state.sound;localStorage.setItem("in2ition_sound",state.sound?"on":"off");$("#soundState").textContent=state.sound?"ON":"OFF"};
$("#resetData").onclick=()=>{if(confirm("Reset IN2ITION progress on this device?")){localStorage.removeItem("in2ition_progress");localStorage.removeItem("in2ition_scores");renderHome();toast("Progress reset")}};
$("#dailyBtn").onclick=()=>startGame("Daily",[IN2ITION_QUESTIONS.Numbers[0],IN2ITION_QUESTIONS.Colours[0],IN2ITION_QUESTIONS.Animals[0]]);
$("#weeklyBtn").onclick=()=>startGame("Weekly",[...IN2ITION_QUESTIONS.Numbers,...IN2ITION_QUESTIONS.Colours,...IN2ITION_QUESTIONS.Animals]);
document.body.className=state.theme==="light"?"light":state.theme==="ocean"?"ocean":"";$("#themeName").textContent=state.theme==="light"?"Light":state.theme==="ocean"?"Ocean":"Neon Night";$("#soundState").textContent=state.sound?"ON":"OFF";renderHome();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}));